# Generated by Django 2.2.7 on 2019-11-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('name', models.CharField(max_length=100, verbose_name='Nome completo')),
                ('cpf', models.IntegerField(primary_key=True, serialize=False, verbose_name='CPF')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'ordering': ['name'],
            },
        ),
    ]
