# Generated by Django 2.2.7 on 2019-11-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='hobbie',
            field=models.CharField(blank=True, max_length=100, verbose_name='Hobbies'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='serie',
            field=models.CharField(blank=True, max_length=100, verbose_name='Series'),
        ),
    ]
