# Generated by Django 2.2.7 on 2019-11-10 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nome', models.CharField(max_length=100, verbose_name='Nome completo')),
                ('nomeResumido', models.CharField(max_length=50, verbose_name='Nome resumido')),
                ('cpf', models.IntegerField(primary_key=True, serialize=False, verbose_name='CPF')),
                ('dataVencimento', models.DateField(verbose_name='Data de vencimento')),
            ],
        ),
    ]
