# Generated by Django 2.2.7 on 2019-11-11 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
